// Code generated by cmd/gen v0.6.4. DO NOT EDIT.

package ta

var retCodeMessages = map[int]string{
	0:    "TA_SUCCESS(0): No error",
	1:    "TA_LIB_NOT_INITIALIZE(1): TA_Initialize was not sucessfully called",
	2:    "TA_BAD_PARAM(2): A parameter is out of range",
	3:    "TA_ALLOC_ERR(3): Possibly out-of-memory",
	4:    "TA_GROUP_NOT_FOUND(4): No Info",
	5:    "TA_FUNC_NOT_FOUND(5): No Info",
	6:    "TA_INVALID_HANDLE(6): No Info",
	7:    "TA_INVALID_PARAM_HOLDER(7): No Info",
	8:    "TA_INVALID_PARAM_HOLDER_TYPE(8): No Info",
	9:    "TA_INVALID_PARAM_FUNCTION(9): No Info",
	10:   "TA_INPUT_NOT_ALL_INITIALIZE(10): No Info",
	11:   "TA_OUTPUT_NOT_ALL_INITIALIZE(11): No Info",
	12:   "TA_OUT_OF_RANGE_START_INDEX(12): No Info",
	13:   "TA_OUT_OF_RANGE_END_INDEX(13): No Info",
	14:   "TA_INVALID_LIST_TYPE(14): No Info",
	15:   "TA_BAD_OBJECT(15): No Info",
	16:   "TA_NOT_SUPPORTED(16): No Info",
	5000: "TA_INTERNAL_ERROR(5000): No Info",
}
