// Code generated by cmd/gen v0.6.4. DO NOT EDIT.

package ta

/*
#include "ta_func.h"
*/
import "C"

// AccbandsLookback returns the number of input values consumed before the first valid output.
func AccbandsLookback(timePeriod int) int {
	return int(C.TA_ACCBANDS_Lookback(C.int(timePeriod)))
}

// AcosLookback returns the number of input values consumed before the first valid output.
func AcosLookback() int {
	return int(C.TA_ACOS_Lookback())
}

// AdLookback returns the number of input values consumed before the first valid output.
func AdLookback() int {
	return int(C.TA_AD_Lookback())
}

// AddLookback returns the number of input values consumed before the first valid output.
func AddLookback() int {
	return int(C.TA_ADD_Lookback())
}

// AdoscLookback returns the number of input values consumed before the first valid output.
func AdoscLookback(fastPeriod int, slowPeriod int) int {
	return int(C.TA_ADOSC_Lookback(C.int(fastPeriod), C.int(slowPeriod)))
}

// AdxLookback returns the number of input values consumed before the first valid output.
func AdxLookback(timePeriod int) int {
	return int(C.TA_ADX_Lookback(C.int(timePeriod)))
}

// AdxrLookback returns the number of input values consumed before the first valid output.
func AdxrLookback(timePeriod int) int {
	return int(C.TA_ADXR_Lookback(C.int(timePeriod)))
}

// ApoLookback returns the number of input values consumed before the first valid output.
func ApoLookback(fastPeriod int, slowPeriod int, mAType int) int {
	return int(C.TA_APO_Lookback(C.int(fastPeriod), C.int(slowPeriod), C.TA_MAType(mAType)))
}

// AroonLookback returns the number of input values consumed before the first valid output.
func AroonLookback(timePeriod int) int {
	return int(C.TA_AROON_Lookback(C.int(timePeriod)))
}

// AroonoscLookback returns the number of input values consumed before the first valid output.
func AroonoscLookback(timePeriod int) int {
	return int(C.TA_AROONOSC_Lookback(C.int(timePeriod)))
}

// AsinLookback returns the number of input values consumed before the first valid output.
func AsinLookback() int {
	return int(C.TA_ASIN_Lookback())
}

// AtanLookback returns the number of input values consumed before the first valid output.
func AtanLookback() int {
	return int(C.TA_ATAN_Lookback())
}

// AtrLookback returns the number of input values consumed before the first valid output.
func AtrLookback(timePeriod int) int {
	return int(C.TA_ATR_Lookback(C.int(timePeriod)))
}

// AvgpriceLookback returns the number of input values consumed before the first valid output.
func AvgpriceLookback() int {
	return int(C.TA_AVGPRICE_Lookback())
}

// AvgdevLookback returns the number of input values consumed before the first valid output.
func AvgdevLookback(timePeriod int) int {
	return int(C.TA_AVGDEV_Lookback(C.int(timePeriod)))
}

// BbandsLookback returns the number of input values consumed before the first valid output.
func BbandsLookback(timePeriod int, nbDevUp float64, nbDevDn float64, mAType int) int {
	return int(C.TA_BBANDS_Lookback(C.int(timePeriod), C.double(nbDevUp), C.double(nbDevDn), C.TA_MAType(mAType)))
}

// BetaLookback returns the number of input values consumed before the first valid output.
func BetaLookback(timePeriod int) int {
	return int(C.TA_BETA_Lookback(C.int(timePeriod)))
}

// BopLookback returns the number of input values consumed before the first valid output.
func BopLookback() int {
	return int(C.TA_BOP_Lookback())
}

// CciLookback returns the number of input values consumed before the first valid output.
func CciLookback(timePeriod int) int {
	return int(C.TA_CCI_Lookback(C.int(timePeriod)))
}

// Cdl2crowsLookback returns the number of input values consumed before the first valid output.
func Cdl2crowsLookback() int {
	return int(C.TA_CDL2CROWS_Lookback())
}

// Cdl3blackcrowsLookback returns the number of input values consumed before the first valid output.
func Cdl3blackcrowsLookback() int {
	return int(C.TA_CDL3BLACKCROWS_Lookback())
}

// Cdl3insideLookback returns the number of input values consumed before the first valid output.
func Cdl3insideLookback() int {
	return int(C.TA_CDL3INSIDE_Lookback())
}

// Cdl3linestrikeLookback returns the number of input values consumed before the first valid output.
func Cdl3linestrikeLookback() int {
	return int(C.TA_CDL3LINESTRIKE_Lookback())
}

// Cdl3outsideLookback returns the number of input values consumed before the first valid output.
func Cdl3outsideLookback() int {
	return int(C.TA_CDL3OUTSIDE_Lookback())
}

// Cdl3starsinsouthLookback returns the number of input values consumed before the first valid output.
func Cdl3starsinsouthLookback() int {
	return int(C.TA_CDL3STARSINSOUTH_Lookback())
}

// Cdl3whitesoldiersLookback returns the number of input values consumed before the first valid output.
func Cdl3whitesoldiersLookback() int {
	return int(C.TA_CDL3WHITESOLDIERS_Lookback())
}

// CdlabandonedbabyLookback returns the number of input values consumed before the first valid output.
func CdlabandonedbabyLookback(penetration float64) int {
	return int(C.TA_CDLABANDONEDBABY_Lookback(C.double(penetration)))
}

// CdladvanceblockLookback returns the number of input values consumed before the first valid output.
func CdladvanceblockLookback() int {
	return int(C.TA_CDLADVANCEBLOCK_Lookback())
}

// CdlbeltholdLookback returns the number of input values consumed before the first valid output.
func CdlbeltholdLookback() int {
	return int(C.TA_CDLBELTHOLD_Lookback())
}

// CdlbreakawayLookback returns the number of input values consumed before the first valid output.
func CdlbreakawayLookback() int {
	return int(C.TA_CDLBREAKAWAY_Lookback())
}

// CdlclosingmarubozuLookback returns the number of input values consumed before the first valid output.
func CdlclosingmarubozuLookback() int {
	return int(C.TA_CDLCLOSINGMARUBOZU_Lookback())
}

// CdlconcealbabyswallLookback returns the number of input values consumed before the first valid output.
func CdlconcealbabyswallLookback() int {
	return int(C.TA_CDLCONCEALBABYSWALL_Lookback())
}

// CdlcounterattackLookback returns the number of input values consumed before the first valid output.
func CdlcounterattackLookback() int {
	return int(C.TA_CDLCOUNTERATTACK_Lookback())
}

// CdldarkcloudcoverLookback returns the number of input values consumed before the first valid output.
func CdldarkcloudcoverLookback(penetration float64) int {
	return int(C.TA_CDLDARKCLOUDCOVER_Lookback(C.double(penetration)))
}

// CdldojiLookback returns the number of input values consumed before the first valid output.
func CdldojiLookback() int {
	return int(C.TA_CDLDOJI_Lookback())
}

// CdldojistarLookback returns the number of input values consumed before the first valid output.
func CdldojistarLookback() int {
	return int(C.TA_CDLDOJISTAR_Lookback())
}

// CdldragonflydojiLookback returns the number of input values consumed before the first valid output.
func CdldragonflydojiLookback() int {
	return int(C.TA_CDLDRAGONFLYDOJI_Lookback())
}

// CdlengulfingLookback returns the number of input values consumed before the first valid output.
func CdlengulfingLookback() int {
	return int(C.TA_CDLENGULFING_Lookback())
}

// CdleveningdojistarLookback returns the number of input values consumed before the first valid output.
func CdleveningdojistarLookback(penetration float64) int {
	return int(C.TA_CDLEVENINGDOJISTAR_Lookback(C.double(penetration)))
}

// CdleveningstarLookback returns the number of input values consumed before the first valid output.
func CdleveningstarLookback(penetration float64) int {
	return int(C.TA_CDLEVENINGSTAR_Lookback(C.double(penetration)))
}

// CdlgapsidesidewhiteLookback returns the number of input values consumed before the first valid output.
func CdlgapsidesidewhiteLookback() int {
	return int(C.TA_CDLGAPSIDESIDEWHITE_Lookback())
}

// CdlgravestonedojiLookback returns the number of input values consumed before the first valid output.
func CdlgravestonedojiLookback() int {
	return int(C.TA_CDLGRAVESTONEDOJI_Lookback())
}

// CdlhammerLookback returns the number of input values consumed before the first valid output.
func CdlhammerLookback() int {
	return int(C.TA_CDLHAMMER_Lookback())
}

// CdlhangingmanLookback returns the number of input values consumed before the first valid output.
func CdlhangingmanLookback() int {
	return int(C.TA_CDLHANGINGMAN_Lookback())
}

// CdlharamiLookback returns the number of input values consumed before the first valid output.
func CdlharamiLookback() int {
	return int(C.TA_CDLHARAMI_Lookback())
}

// CdlharamicrossLookback returns the number of input values consumed before the first valid output.
func CdlharamicrossLookback() int {
	return int(C.TA_CDLHARAMICROSS_Lookback())
}

// CdlhighwaveLookback returns the number of input values consumed before the first valid output.
func CdlhighwaveLookback() int {
	return int(C.TA_CDLHIGHWAVE_Lookback())
}

// CdlhikkakeLookback returns the number of input values consumed before the first valid output.
func CdlhikkakeLookback() int {
	return int(C.TA_CDLHIKKAKE_Lookback())
}

// CdlhikkakemodLookback returns the number of input values consumed before the first valid output.
func CdlhikkakemodLookback() int {
	return int(C.TA_CDLHIKKAKEMOD_Lookback())
}

// CdlhomingpigeonLookback returns the number of input values consumed before the first valid output.
func CdlhomingpigeonLookback() int {
	return int(C.TA_CDLHOMINGPIGEON_Lookback())
}

// Cdlidentical3crowsLookback returns the number of input values consumed before the first valid output.
func Cdlidentical3crowsLookback() int {
	return int(C.TA_CDLIDENTICAL3CROWS_Lookback())
}

// CdlinneckLookback returns the number of input values consumed before the first valid output.
func CdlinneckLookback() int {
	return int(C.TA_CDLINNECK_Lookback())
}

// CdlinvertedhammerLookback returns the number of input values consumed before the first valid output.
func CdlinvertedhammerLookback() int {
	return int(C.TA_CDLINVERTEDHAMMER_Lookback())
}

// CdlkickingLookback returns the number of input values consumed before the first valid output.
func CdlkickingLookback() int {
	return int(C.TA_CDLKICKING_Lookback())
}

// CdlkickingbylengthLookback returns the number of input values consumed before the first valid output.
func CdlkickingbylengthLookback() int {
	return int(C.TA_CDLKICKINGBYLENGTH_Lookback())
}

// CdlladderbottomLookback returns the number of input values consumed before the first valid output.
func CdlladderbottomLookback() int {
	return int(C.TA_CDLLADDERBOTTOM_Lookback())
}

// CdllongleggeddojiLookback returns the number of input values consumed before the first valid output.
func CdllongleggeddojiLookback() int {
	return int(C.TA_CDLLONGLEGGEDDOJI_Lookback())
}

// CdllonglineLookback returns the number of input values consumed before the first valid output.
func CdllonglineLookback() int {
	return int(C.TA_CDLLONGLINE_Lookback())
}

// CdlmarubozuLookback returns the number of input values consumed before the first valid output.
func CdlmarubozuLookback() int {
	return int(C.TA_CDLMARUBOZU_Lookback())
}

// CdlmatchinglowLookback returns the number of input values consumed before the first valid output.
func CdlmatchinglowLookback() int {
	return int(C.TA_CDLMATCHINGLOW_Lookback())
}

// CdlmatholdLookback returns the number of input values consumed before the first valid output.
func CdlmatholdLookback(penetration float64) int {
	return int(C.TA_CDLMATHOLD_Lookback(C.double(penetration)))
}

// CdlmorningdojistarLookback returns the number of input values consumed before the first valid output.
func CdlmorningdojistarLookback(penetration float64) int {
	return int(C.TA_CDLMORNINGDOJISTAR_Lookback(C.double(penetration)))
}

// CdlmorningstarLookback returns the number of input values consumed before the first valid output.
func CdlmorningstarLookback(penetration float64) int {
	return int(C.TA_CDLMORNINGSTAR_Lookback(C.double(penetration)))
}

// CdlonneckLookback returns the number of input values consumed before the first valid output.
func CdlonneckLookback() int {
	return int(C.TA_CDLONNECK_Lookback())
}

// CdlpiercingLookback returns the number of input values consumed before the first valid output.
func CdlpiercingLookback() int {
	return int(C.TA_CDLPIERCING_Lookback())
}

// CdlrickshawmanLookback returns the number of input values consumed before the first valid output.
func CdlrickshawmanLookback() int {
	return int(C.TA_CDLRICKSHAWMAN_Lookback())
}

// Cdlrisefall3methodsLookback returns the number of input values consumed before the first valid output.
func Cdlrisefall3methodsLookback() int {
	return int(C.TA_CDLRISEFALL3METHODS_Lookback())
}

// CdlseparatinglinesLookback returns the number of input values consumed before the first valid output.
func CdlseparatinglinesLookback() int {
	return int(C.TA_CDLSEPARATINGLINES_Lookback())
}

// CdlshootingstarLookback returns the number of input values consumed before the first valid output.
func CdlshootingstarLookback() int {
	return int(C.TA_CDLSHOOTINGSTAR_Lookback())
}

// CdlshortlineLookback returns the number of input values consumed before the first valid output.
func CdlshortlineLookback() int {
	return int(C.TA_CDLSHORTLINE_Lookback())
}

// CdlspinningtopLookback returns the number of input values consumed before the first valid output.
func CdlspinningtopLookback() int {
	return int(C.TA_CDLSPINNINGTOP_Lookback())
}

// CdlstalledpatternLookback returns the number of input values consumed before the first valid output.
func CdlstalledpatternLookback() int {
	return int(C.TA_CDLSTALLEDPATTERN_Lookback())
}

// CdlsticksandwichLookback returns the number of input values consumed before the first valid output.
func CdlsticksandwichLookback() int {
	return int(C.TA_CDLSTICKSANDWICH_Lookback())
}

// CdltakuriLookback returns the number of input values consumed before the first valid output.
func CdltakuriLookback() int {
	return int(C.TA_CDLTAKURI_Lookback())
}

// CdltasukigapLookback returns the number of input values consumed before the first valid output.
func CdltasukigapLookback() int {
	return int(C.TA_CDLTASUKIGAP_Lookback())
}

// CdlthrustingLookback returns the number of input values consumed before the first valid output.
func CdlthrustingLookback() int {
	return int(C.TA_CDLTHRUSTING_Lookback())
}

// CdltristarLookback returns the number of input values consumed before the first valid output.
func CdltristarLookback() int {
	return int(C.TA_CDLTRISTAR_Lookback())
}

// Cdlunique3riverLookback returns the number of input values consumed before the first valid output.
func Cdlunique3riverLookback() int {
	return int(C.TA_CDLUNIQUE3RIVER_Lookback())
}

// Cdlupsidegap2crowsLookback returns the number of input values consumed before the first valid output.
func Cdlupsidegap2crowsLookback() int {
	return int(C.TA_CDLUPSIDEGAP2CROWS_Lookback())
}

// Cdlxsidegap3methodsLookback returns the number of input values consumed before the first valid output.
func Cdlxsidegap3methodsLookback() int {
	return int(C.TA_CDLXSIDEGAP3METHODS_Lookback())
}

// CeilLookback returns the number of input values consumed before the first valid output.
func CeilLookback() int {
	return int(C.TA_CEIL_Lookback())
}

// CmoLookback returns the number of input values consumed before the first valid output.
func CmoLookback(timePeriod int) int {
	return int(C.TA_CMO_Lookback(C.int(timePeriod)))
}

// CorrelLookback returns the number of input values consumed before the first valid output.
func CorrelLookback(timePeriod int) int {
	return int(C.TA_CORREL_Lookback(C.int(timePeriod)))
}

// CosLookback returns the number of input values consumed before the first valid output.
func CosLookback() int {
	return int(C.TA_COS_Lookback())
}

// CoshLookback returns the number of input values consumed before the first valid output.
func CoshLookback() int {
	return int(C.TA_COSH_Lookback())
}

// DemaLookback returns the number of input values consumed before the first valid output.
func DemaLookback(timePeriod int) int {
	return int(C.TA_DEMA_Lookback(C.int(timePeriod)))
}

// DivLookback returns the number of input values consumed before the first valid output.
func DivLookback() int {
	return int(C.TA_DIV_Lookback())
}

// DxLookback returns the number of input values consumed before the first valid output.
func DxLookback(timePeriod int) int {
	return int(C.TA_DX_Lookback(C.int(timePeriod)))
}

// EmaLookback returns the number of input values consumed before the first valid output.
func EmaLookback(timePeriod int) int {
	return int(C.TA_EMA_Lookback(C.int(timePeriod)))
}

// ExpLookback returns the number of input values consumed before the first valid output.
func ExpLookback() int {
	return int(C.TA_EXP_Lookback())
}

// FloorLookback returns the number of input values consumed before the first valid output.
func FloorLookback() int {
	return int(C.TA_FLOOR_Lookback())
}

// ImiLookback returns the number of input values consumed before the first valid output.
func ImiLookback(timePeriod int) int {
	return int(C.TA_IMI_Lookback(C.int(timePeriod)))
}

// KamaLookback returns the number of input values consumed before the first valid output.
func KamaLookback(timePeriod int) int {
	return int(C.TA_KAMA_Lookback(C.int(timePeriod)))
}

// LinearregLookback returns the number of input values consumed before the first valid output.
func LinearregLookback(timePeriod int) int {
	return int(C.TA_LINEARREG_Lookback(C.int(timePeriod)))
}

// LnLookback returns the number of input values consumed before the first valid output.
func LnLookback() int {
	return int(C.TA_LN_Lookback())
}

// Log10Lookback returns the number of input values consumed before the first valid output.
func Log10Lookback() int {
	return int(C.TA_LOG10_Lookback())
}

// MaLookback returns the number of input values consumed before the first valid output.
func MaLookback(timePeriod int, mAType int) int {
	return int(C.TA_MA_Lookback(C.int(timePeriod), C.TA_MAType(mAType)))
}

// MacdLookback returns the number of input values consumed before the first valid output.
func MacdLookback(fastPeriod int, slowPeriod int, signalPeriod int) int {
	return int(C.TA_MACD_Lookback(C.int(fastPeriod), C.int(slowPeriod), C.int(signalPeriod)))
}

// MacdextLookback returns the number of input values consumed before the first valid output.
func MacdextLookback(fastPeriod int, fastMAType int, slowPeriod int, slowMAType int, signalPeriod int, signalMAType int) int {
	return int(C.TA_MACDEXT_Lookback(C.int(fastPeriod), C.TA_MAType(fastMAType), C.int(slowPeriod), C.TA_MAType(slowMAType), C.int(signalPeriod), C.TA_MAType(signalMAType)))
}

// MacdfixLookback returns the number of input values consumed before the first valid output.
func MacdfixLookback(signalPeriod int) int {
	return int(C.TA_MACDFIX_Lookback(C.int(signalPeriod)))
}

// MamaLookback returns the number of input values consumed before the first valid output.
func MamaLookback(fastLimit float64, slowLimit float64) int {
	return int(C.TA_MAMA_Lookback(C.double(fastLimit), C.double(slowLimit)))
}

// MavpLookback returns the number of input values consumed before the first valid output.
func MavpLookback(minPeriod int, maxPeriod int, mAType int) int {
	return int(C.TA_MAVP_Lookback(C.int(minPeriod), C.int(maxPeriod), C.TA_MAType(mAType)))
}

// MaxLookback returns the number of input values consumed before the first valid output.
func MaxLookback(timePeriod int) int {
	return int(C.TA_MAX_Lookback(C.int(timePeriod)))
}

// MaxindexLookback returns the number of input values consumed before the first valid output.
func MaxindexLookback(timePeriod int) int {
	return int(C.TA_MAXINDEX_Lookback(C.int(timePeriod)))
}

// MedpriceLookback returns the number of input values consumed before the first valid output.
func MedpriceLookback() int {
	return int(C.TA_MEDPRICE_Lookback())
}

// MfiLookback returns the number of input values consumed before the first valid output.
func MfiLookback(timePeriod int) int {
	return int(C.TA_MFI_Lookback(C.int(timePeriod)))
}

// MidpointLookback returns the number of input values consumed before the first valid output.
func MidpointLookback(timePeriod int) int {
	return int(C.TA_MIDPOINT_Lookback(C.int(timePeriod)))
}

// MidpriceLookback returns the number of input values consumed before the first valid output.
func MidpriceLookback(timePeriod int) int {
	return int(C.TA_MIDPRICE_Lookback(C.int(timePeriod)))
}

// MinLookback returns the number of input values consumed before the first valid output.
func MinLookback(timePeriod int) int {
	return int(C.TA_MIN_Lookback(C.int(timePeriod)))
}

// MinindexLookback returns the number of input values consumed before the first valid output.
func MinindexLookback(timePeriod int) int {
	return int(C.TA_MININDEX_Lookback(C.int(timePeriod)))
}

// MinmaxLookback returns the number of input values consumed before the first valid output.
func MinmaxLookback(timePeriod int) int {
	return int(C.TA_MINMAX_Lookback(C.int(timePeriod)))
}

// MinmaxindexLookback returns the number of input values consumed before the first valid output.
func MinmaxindexLookback(timePeriod int) int {
	return int(C.TA_MINMAXINDEX_Lookback(C.int(timePeriod)))
}

// MomLookback returns the number of input values consumed before the first valid output.
func MomLookback(timePeriod int) int {
	return int(C.TA_MOM_Lookback(C.int(timePeriod)))
}

// MultLookback returns the number of input values consumed before the first valid output.
func MultLookback() int {
	return int(C.TA_MULT_Lookback())
}

// NatrLookback returns the number of input values consumed before the first valid output.
func NatrLookback(timePeriod int) int {
	return int(C.TA_NATR_Lookback(C.int(timePeriod)))
}

// ObvLookback returns the number of input values consumed before the first valid output.
func ObvLookback() int {
	return int(C.TA_OBV_Lookback())
}

// PpoLookback returns the number of input values consumed before the first valid output.
func PpoLookback(fastPeriod int, slowPeriod int, mAType int) int {
	return int(C.TA_PPO_Lookback(C.int(fastPeriod), C.int(slowPeriod), C.TA_MAType(mAType)))
}

// RocLookback returns the number of input values consumed before the first valid output.
func RocLookback(timePeriod int) int {
	return int(C.TA_ROC_Lookback(C.int(timePeriod)))
}

// RocpLookback returns the number of input values consumed before the first valid output.
func RocpLookback(timePeriod int) int {
	return int(C.TA_ROCP_Lookback(C.int(timePeriod)))
}

// RocrLookback returns the number of input values consumed before the first valid output.
func RocrLookback(timePeriod int) int {
	return int(C.TA_ROCR_Lookback(C.int(timePeriod)))
}

// Rocr100Lookback returns the number of input values consumed before the first valid output.
func Rocr100Lookback(timePeriod int) int {
	return int(C.TA_ROCR100_Lookback(C.int(timePeriod)))
}

// RsiLookback returns the number of input values consumed before the first valid output.
func RsiLookback(timePeriod int) int {
	return int(C.TA_RSI_Lookback(C.int(timePeriod)))
}

// SarLookback returns the number of input values consumed before the first valid output.
func SarLookback(acceleration float64, maximum float64) int {
	return int(C.TA_SAR_Lookback(C.double(acceleration), C.double(maximum)))
}

// SarextLookback returns the number of input values consumed before the first valid output.
func SarextLookback(startValue float64, offsetOnReverse float64, accelerationInitLong float64, accelerationLong float64, accelerationMaxLong float64, accelerationInitShort float64, accelerationShort float64, accelerationMaxShort float64) int {
	return int(C.TA_SAREXT_Lookback(C.double(startValue), C.double(offsetOnReverse), C.double(accelerationInitLong), C.double(accelerationLong), C.double(accelerationMaxLong), C.double(accelerationInitShort), C.double(accelerationShort), C.double(accelerationMaxShort)))
}

// SinLookback returns the number of input values consumed before the first valid output.
func SinLookback() int {
	return int(C.TA_SIN_Lookback())
}

// SinhLookback returns the number of input values consumed before the first valid output.
func SinhLookback() int {
	return int(C.TA_SINH_Lookback())
}

// SmaLookback returns the number of input values consumed before the first valid output.
func SmaLookback(timePeriod int) int {
	return int(C.TA_SMA_Lookback(C.int(timePeriod)))
}

// SqrtLookback returns the number of input values consumed before the first valid output.
func SqrtLookback() int {
	return int(C.TA_SQRT_Lookback())
}

// StddevLookback returns the number of input values consumed before the first valid output.
func StddevLookback(timePeriod int, nbDev float64) int {
	return int(C.TA_STDDEV_Lookback(C.int(timePeriod), C.double(nbDev)))
}

// StochLookback returns the number of input values consumed before the first valid output.
func StochLookback(fastK_Period int, slowK_Period int, slowK_MAType int, slowD_Period int, slowD_MAType int) int {
	return int(C.TA_STOCH_Lookback(C.int(fastK_Period), C.int(slowK_Period), C.TA_MAType(slowK_MAType), C.int(slowD_Period), C.TA_MAType(slowD_MAType)))
}

// StochfLookback returns the number of input values consumed before the first valid output.
func StochfLookback(fastK_Period int, fastD_Period int, fastD_MAType int) int {
	return int(C.TA_STOCHF_Lookback(C.int(fastK_Period), C.int(fastD_Period), C.TA_MAType(fastD_MAType)))
}

// StochrsiLookback returns the number of input values consumed before the first valid output.
func StochrsiLookback(timePeriod int, fastK_Period int, fastD_Period int, fastD_MAType int) int {
	return int(C.TA_STOCHRSI_Lookback(C.int(timePeriod), C.int(fastK_Period), C.int(fastD_Period), C.TA_MAType(fastD_MAType)))
}

// SubLookback returns the number of input values consumed before the first valid output.
func SubLookback() int {
	return int(C.TA_SUB_Lookback())
}

// SumLookback returns the number of input values consumed before the first valid output.
func SumLookback(timePeriod int) int {
	return int(C.TA_SUM_Lookback(C.int(timePeriod)))
}

// T3Lookback returns the number of input values consumed before the first valid output.
func T3Lookback(timePeriod int, vFactor float64) int {
	return int(C.TA_T3_Lookback(C.int(timePeriod), C.double(vFactor)))
}

// TanLookback returns the number of input values consumed before the first valid output.
func TanLookback() int {
	return int(C.TA_TAN_Lookback())
}

// TanhLookback returns the number of input values consumed before the first valid output.
func TanhLookback() int {
	return int(C.TA_TANH_Lookback())
}

// TemaLookback returns the number of input values consumed before the first valid output.
func TemaLookback(timePeriod int) int {
	return int(C.TA_TEMA_Lookback(C.int(timePeriod)))
}

// TrangeLookback returns the number of input values consumed before the first valid output.
func TrangeLookback() int {
	return int(C.TA_TRANGE_Lookback())
}

// TrimaLookback returns the number of input values consumed before the first valid output.
func TrimaLookback(timePeriod int) int {
	return int(C.TA_TRIMA_Lookback(C.int(timePeriod)))
}

// TrixLookback returns the number of input values consumed before the first valid output.
func TrixLookback(timePeriod int) int {
	return int(C.TA_TRIX_Lookback(C.int(timePeriod)))
}

// TsfLookback returns the number of input values consumed before the first valid output.
func TsfLookback(timePeriod int) int {
	return int(C.TA_TSF_Lookback(C.int(timePeriod)))
}

// TyppriceLookback returns the number of input values consumed before the first valid output.
func TyppriceLookback() int {
	return int(C.TA_TYPPRICE_Lookback())
}

// UltoscLookback returns the number of input values consumed before the first valid output.
func UltoscLookback(timePeriod1 int, timePeriod2 int, timePeriod3 int) int {
	return int(C.TA_ULTOSC_Lookback(C.int(timePeriod1), C.int(timePeriod2), C.int(timePeriod3)))
}

// VarLookback returns the number of input values consumed before the first valid output.
func VarLookback(timePeriod int, nbDev float64) int {
	return int(C.TA_VAR_Lookback(C.int(timePeriod), C.double(nbDev)))
}

// WclpriceLookback returns the number of input values consumed before the first valid output.
func WclpriceLookback() int {
	return int(C.TA_WCLPRICE_Lookback())
}

// WillrLookback returns the number of input values consumed before the first valid output.
func WillrLookback(timePeriod int) int {
	return int(C.TA_WILLR_Lookback(C.int(timePeriod)))
}

// WmaLookback returns the number of input values consumed before the first valid output.
func WmaLookback(timePeriod int) int {
	return int(C.TA_WMA_Lookback(C.int(timePeriod)))
}
